#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Run rumor-topic search tasks with MediaCrawler.

This helper reads task files generated by rumor_crawler, for example
``data/topic_search_tasks_all.json``, and executes each keyword as an isolated
MediaCrawler search task. It keeps a checkpoint so a long cross-platform run can
be resumed safely.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_TASKS_FILE = BASE_DIR.parent / "rumor_crawler" / "data" / "topic_search_tasks_all.json"
DEFAULT_OUTPUT_DIR = BASE_DIR.parent / "rumor_crawler" / "data" / "mediacrawler"
DEFAULT_CHECKPOINT_FILE = BASE_DIR.parent / "rumor_crawler" / "state" / "topic_crawler_checkpoint.json"
DEFAULT_CHROME_PATH = Path(r"C:\Users\USER\AppData\Local\Google\Chrome\Application\chrome.exe")
PLATFORM_ALIASES = {
    "douyin": "dy",
    "kuaishou": "ks",
    "weibo": "wb",
    "bilibili": "bili",
    "rednote": "xhs",
    "xiaohongshu": "xhs",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="执行 rumor_crawler 题材级跨平台搜索任务")
    parser.add_argument("--tasks-file", default=str(DEFAULT_TASKS_FILE))
    parser.add_argument("--platforms", default="dy,ks,wb,bili,xhs")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--checkpoint-file", default=str(DEFAULT_CHECKPOINT_FILE))
    parser.add_argument("--max-notes-count", type=int, default=3)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--python", default=str(BASE_DIR / ".venv" / "Scripts" / "python.exe"))
    parser.add_argument("--chrome-path", default=str(DEFAULT_CHROME_PATH))
    parser.add_argument("--weibo-cdp", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--comments", action=argparse.BooleanOptionalAction, default=False)
    return parser.parse_args()


def normalize_platform(value: str) -> str:
    raw = value.strip()
    return PLATFORM_ALIASES.get(raw, raw)


def load_tasks(path: Path, platforms: set[str], limit: int) -> list[dict[str, str]]:
    rows = json.loads(path.read_text(encoding="utf-8"))
    tasks: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for row in rows:
        platform = normalize_platform(str(row.get("platform") or ""))
        keyword = str(row.get("keyword") or "").strip()
        if platform not in platforms or not keyword:
            continue
        key = (platform, keyword)
        if key in seen:
            continue
        seen.add(key)
        tasks.append(
            {
                "task_id": str(row.get("task_id") or f"{platform}:{keyword}"),
                "platform": platform,
                "keyword": keyword,
            }
        )
        if limit and len(tasks) >= limit:
            break
    return tasks


def load_checkpoint(path: Path) -> dict[str, dict[str, dict[str, str]]]:
    if not path.exists():
        return {"done_tasks": {}, "failed_tasks": {}}
    data = json.loads(path.read_text(encoding="utf-8"))
    data.setdefault("done_tasks", {})
    data.setdefault("failed_tasks", {})
    return data


def save_checkpoint(path: Path, checkpoint: dict[str, dict[str, dict[str, str]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(checkpoint, ensure_ascii=False, indent=2), encoding="utf-8")


def build_command(args: argparse.Namespace, platform: str, keyword: str) -> list[str]:
    argv = [
        "main.py",
        "--platform",
        platform,
        "--lt",
        "qrcode",
        "--type",
        "search",
        "--keywords",
        keyword,
        "--crawler_max_notes_count",
        str(args.max_notes_count),
        "--get_comment",
        "true" if args.comments else "false",
        "--get_sub_comment",
        "false",
        "--save_data_option",
        "jsonl",
        "--save_data_path",
        str(Path(args.output_dir)),
        "--headless",
        "true" if args.headless else "false",
    ]
    code = (
        "import sys; "
        f"sys.argv={argv!r}; "
        "import main as m; import config; "
        + platform_runtime_config(args, platform)
        + "from tools.app_runner import run; "
        "run(m.main, m.async_cleanup, cleanup_timeout_seconds=15.0)"
    )
    return [str(Path(args.python)), "-c", code]


def platform_runtime_config(args: argparse.Namespace, platform: str) -> str:
    pieces = [
        "config.ENABLE_GET_MEIDAS=False; ",
        "config.SAVE_LOGIN_STATE=True; ",
    ]
    if platform == "wb" and args.weibo_cdp:
        pieces.extend(
            [
                "config.ENABLE_CDP_MODE=True; ",
                "config.CDP_CONNECT_EXISTING=False; ",
                f"config.CUSTOM_BROWSER_PATH={str(Path(args.chrome_path))!r}; ",
                "config.AUTO_CLOSE_BROWSER=True; ",
            ]
        )
    return "".join(pieces)


def run_task(args: argparse.Namespace, task: dict[str, str]) -> int:
    command = build_command(args, task["platform"], task["keyword"])
    print(f"[topic] {task['platform']} 搜索关键词: {task['keyword']}", flush=True)
    if args.dry_run:
        print(" ".join(command), flush=True)
        return 0
    completed = subprocess.run(command, cwd=str(BASE_DIR), check=False)
    return completed.returncode


def main() -> int:
    args = parse_args()
    platforms = {normalize_platform(item) for item in args.platforms.split(",") if item.strip()}
    tasks = load_tasks(Path(args.tasks_file), platforms, args.limit)
    if not tasks:
        print("没有可执行的题材搜索任务。", file=sys.stderr)
        return 1

    checkpoint_path = Path(args.checkpoint_file)
    checkpoint = {"done_tasks": {}, "failed_tasks": {}} if args.dry_run else load_checkpoint(checkpoint_path)
    failed = 0
    skipped = 0
    for task in tasks:
        task_id = task["task_id"]
        if not args.force and task_id in checkpoint["done_tasks"]:
            skipped += 1
            print(f"[topic] 跳过已完成任务: {task['platform']} {task['keyword']}", flush=True)
            continue
        return_code = run_task(args, task)
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if return_code == 0:
            checkpoint["done_tasks"][task_id] = {
                "platform": task["platform"],
                "keyword": task["keyword"],
                "time": now,
            }
            checkpoint["failed_tasks"].pop(task_id, None)
        else:
            failed += 1
            checkpoint["failed_tasks"][task_id] = {
                "platform": task["platform"],
                "keyword": task["keyword"],
                "time": now,
                "return_code": str(return_code),
            }
        if not args.dry_run:
            save_checkpoint(checkpoint_path, checkpoint)
    print(f"完成题材搜索任务: total={len(tasks)} skipped={skipped} failed={failed}", flush=True)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
